### ISSUE TITLE
BaseEntity에 정의한 속성들의 타입 변경 추천?

### ISSUE THREAD

**Issue by SungbinYang** [Pepe6bf/spadeworker#75]
BaseEntity에 정의한 createdBy, updatedBy 변수 타입을 String에서 User로 변경하면 어떨까요? 조금 더 객체지향적으로 구성도 되는것 같은것 같아서 변경 추천 드립니다. 물론 제 생각이 옳지 않을 수 있지만 의견 전달 드립니다!

**Comment by kelly6bf** [comment]
앗!! 의견 감사합니다 성빈님!! ~By 컬럼에 경우 우선 해당 리소스의 생성자가 누구인지만 식별하기 위해 User 속성 중 Unique한 값인 PersonalId를 넣었는데 생각해보니 User를 대입해도 괜찮을거 같네요!! 주신 의견 반영해서 좀 더 고민해보겠습니다! 감사합니다!
